"""movie

Revision ID: 8994bba16e5c
Revises: 
Create Date: 2022-03-16 18:01:41.385236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8994bba16e5c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=True),
        sa.Column("genres", sa.String(length=400), nullable=True),
        sa.PrimaryKeyConstraint("movie_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie")
    # ### end Alembic commands ###
